manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gustberchmans
      url-base: https://github.com/gustberchmans
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: moth-hybrid-zmk
      remote: gustberchmans
      revision: main
  self:
    path: config
