manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gustberchmans
      url-base: gustberchmans
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-component-xiao-ble-plus
      remote: gustberchmans
      revision: main
  self:
    path: config
